version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
    external: true